=== SNEEManchester/snee/src/main/resources/schema/network-topology.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://dias-mc.cs.manchester.ac.uk" 
xmlns="http://dias-mc.cs.manchester.ac.uk"
elementFormDefault="qualified">

<xs:element name="network-topology">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="units">
			    <xs:complexType>
			    	<xs:sequence>
						<xs:element name="energy" type="energyUnits"/>
						<xs:element name="memory" type="memoryUnits"/>
						<xs:element name="time" type="timeUnits"/>
			      	</xs:sequence>
			    </xs:complexType>
			</xs:element>
			
			<xs:element name="radio-links">
			    <xs:complexType>
			    	<xs:sequence>
				<xs:element name="radio-link" maxOccurs="unbounded">
				    <xs:complexType>
						<xs:attribute name="source">
							<xs:simpleType>
							  <xs:restriction base="xs:decimal">
							    <xs:minInclusive value="0"/>
							  </xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						
						<xs:attribute name="dest">
							<xs:simpleType>
							  <xs:restriction base="xs:decimal">
							    <xs:minInclusive value="0"/>
							  </xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						
						
						<xs:attribute name="bidirectional" type="xs:boolean" default="true"/>

						<xs:attribute name="energy">
							<xs:simpleType>
							  <xs:restriction base="xs:decimal">
							    <xs:minInclusive value="0"/>
							  </xs:restriction>
							</xs:simpleType>
						</xs:attribute>

						<xs:attribute name="time">
							<xs:simpleType>
							  <xs:restriction base="xs:decimal">
							    <xs:minInclusive value="0"/>
							  </xs:restriction>
							</xs:simpleType>
						</xs:attribute>
				
						<xs:attribute name="radio-loss">
							<xs:simpleType>
							  <xs:restriction base="xs:decimal">
							    <xs:minInclusive value="0"/>
							    <xs:maxInclusive value="1"/>
							  </xs:restriction>
							</xs:simpleType>
						</xs:attribute>
				    </xs:complexType>				
				</xs:element>
			      	</xs:sequence>
			    </xs:complexType>
			</xs:element>						
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:simpleType name="timeUnits">
  <xs:restriction base="xs:string">
    <xs:enumeration value="MILLISECONDS"/>
    <xs:enumeration value="SECONDS"/>
    <xs:enumeration value="MINUTES"/>
    <xs:enumeration value="HOURS"/>
    <xs:enumeration value="DAYS"/>
    <xs:enumeration value="MONTHS"/>
    <xs:enumeration value="YEARS"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="energyUnits">
  <xs:restriction base="xs:string">
    <xs:enumeration value="MILLIJOULES"/>
    <xs:enumeration value="JOULES"/>
    <xs:enumeration value="KILOJOULES"/>
    <xs:enumeration value="MEGAJOULES"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="memoryUnits">
  <xs:restriction base="xs:string">
    <xs:enumeration value="BYTES"/>
    <xs:enumeration value="KILOBYTES"/>
    <xs:enumeration value="MEGABYTES"/>
  </xs:restriction>
</xs:simpleType>


</xs:schema>

=== SNEEManchester/snee/clients/failedNodeEvalClientTimeIntergrated/src/main/resources/testsSize100/wsn_query217.xml
<?xml version="1.0"?>

<network-topology
xmlns="http://snee.cs.manchester.ac.uk"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://snee.cs.manchester.ac.uk network-topology.xsd">

<units>
	<energy>MILLIJOULES</energy>
	<memory>BYTES</memory>
	<time>MILLISECONDS</time>
</units>

<radio-links>
	<radio-link source="0" dest="1" bidirectional="true" energy="14" time="14" radio-loss="0"/>
	<radio-link source="0" dest="4" bidirectional="true" energy="71" time="24" radio-loss="0"/>
	<radio-link source="0" dest="5" bidirectional="true" energy="102" time="28" radio-loss="0"/>
	<radio-link source="0" dest="6" bidirectional="true" energy="4" time="3" radio-loss="0"/>
	<radio-link source="0" dest="7" bidirectional="true" energy="97" time="27" radio-loss="0"/>
	<radio-link source="0" dest="9" bidirectional="true" energy="2" time="2" radio-loss="0"/>
	<radio-link source="0" dest="10" bidirectional="true" energy="120" time="30" radio-loss="0"/>
	<radio-link source="0" dest="11" bidirectional="true" energy="15" time="16" radio-loss="0"/>
	<radio-link source="0" dest="13" bidirectional="true" energy="14" time="15" radio-loss="0"/>
	<radio-link source="0" dest="14" bidirectional="true" energy="9" time="7" radio-loss="0"/>
	<radio-link source="1" dest="3" bidirectional="true" energy="105" time="28" radio-loss="0"/>
	<radio-link source="1" dest="4" bidirectional="true" energy="86" time="26" radio-loss="0"/>
	<radio-link source="1" dest="6" bidirectional="true" energy="14" time="14" radio-loss="0"/>
	<radio-link source="1" dest="8" bidirectional="true" energy="34" time="20" radio-loss="0"/>
	<radio-link source="1" dest="9" bidirectional="true" energy="15" time="17" radio-loss="0"/>
	<radio-link source="2" dest="8" bidirectional="true" energy="14" time="14" radio-loss="0"/>
	<radio-link source="2" dest="13" bidirectional="true" energy="71" time="24" radio-loss="0"/>
	<radio-link source="3" dest="6" bidirectional="true" energy="13" time="13" radio-loss="0"/>
	<radio-link source="4" dest="6" bidirectional="true" energy="99" time="27" radio-loss="0"/>
	<radio-link source="4" dest="13" bidirectional="true" energy="109" time="29" radio-loss="0"/>
	<radio-link source="5" dest="6" bidirectional="true" energy="99" time="27" radio-loss="0"/>
	<radio-link source="5" dest="12" bidirectional="true" energy="115" time="30" radio-loss="0"/>
	<radio-link source="6" dest="10" bidirectional="true" energy="140" time="34" radio-loss="0"/>
	<radio-link source="6" dest="13" bidirectional="true" energy="15" time="16" radio-loss="0"/>
	<radio-link source="9" dest="12" bidirectional="true" energy="43" time="21" radio-loss="0"/>
	<radio-link source="9" dest="13" bidirectional="true" energy="13" time="13" radio-loss="0"/>

</radio-links>
		
</network-topology>
