=== SNEEManchester/snee/snee/src/main/resources/schema/logical-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--  Copyright (c) The University of Manchester, 2010. -->
<!-- 
  SNEE (Sensor NEtwork Engine)                                              
  http://snee.cs.manchester.ac.uk/                                          
  http://code.google.com/p/snee                                             
                                                                            
  Release 1.x, 2009, under New BSD License.                                 
                                                                            
  Copyright (c) 2009, University of Manchester                              
  All rights reserved.                                                      
                                                                            
  Redistribution and use in source and binary forms, with or without        
  modification, are permitted provided that the following conditions are    
  met: Redistributions of source code must retain the above copyright       
  notice, this list of conditions and the following disclaimer.             
  Redistributions in binary form must reproduce the above copyright notice, 
  this list of conditions and the following disclaimer in the documentation 
  and/or other materials provided with the distribution.                    
  Neither the name of the University of Manchester nor the names of its     
  contributors may be used to endorse or promote products derived from this 
  software without specific prior written permission.                       
                                                                            
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS   
  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR    
  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR          
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,     
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,       
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR        
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              	
 -->

<xs:schema targetNamespace="http://snee.cs.man.ac.uk/namespace/logical-schema" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://snee.cs.man.ac.uk/namespace/logical-schema">
	
	<xs:simpleType name="sneeqlDatatypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="timestamp"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="streamType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pull"/>
			<xs:enumeration value="push"/>
		</xs:restriction>
	</xs:simpleType>
	
    <xs:complexType name="columnType">
		<xs:sequence>
			<xs:element name="type" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="class" type="sneeqlDatatypeType" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
    	<xs:attribute name="name" use="required" type="xs:string"/>
	</xs:complexType>	
	<xs:element name="column" type="columnType"/>

	<xs:complexType name="extentType">
		<xs:sequence>
			<xs:element ref="column" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string"/>
	</xs:complexType>
	<xs:element name="table" type="extentType"/>
	
	<xs:complexType name="streamExtentType">
		<xs:complexContent>
			<xs:extension base="extentType">
				<xs:attribute name="type" use="required" type="streamType"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="stream" type="streamExtentType"/>
    
    <xs:element name="schema">
    	<xs:complexType>
    		<xs:choice minOccurs="1" maxOccurs="unbounded">
    			<xs:element ref="stream"/>
    			<xs:element ref="table"/>
    		</xs:choice>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== SNEEManchester/snee/snee/compiler/src/test/resources/etc/logical-schema.xml
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://snee.cs.man.ac.uk/namespace/logical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/logical-schema ../schema/logical-schema.xsd">

      <stream name="TestStream" type="push">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="integerColumn">
          	<type class ="integer"/>
         </column>
         <column name="floatColumn">
          	<type class ="float"/>
         </column>
         <column name="stringColumn">
          	<type class ="string"/>
         </column>
         <column name="boolColumn">
          	<type class ="boolean"/>
         </column>
     </stream>

      <stream name="PullStream" type="pull">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="integerColumn">
          	<type class ="integer"/>
         </column>
         <column name="floatColumn">
          	<type class ="float"/>
         </column>
         <column name="stringColumn">
          	<type class ="string"/>
         </column>
         <column name="boolColumn">
          	<type class ="boolean"/>
         </column>
     </stream>

      <stream name="PushStream" type="push">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="integerColumn">
          	<type class ="integer"/>
         </column>
         <column name="floatColumn">
          	<type class ="float"/>
         </column>
         <column name="stringColumn">
          	<type class ="string"/>
         </column>
         <column name="boolColumn">
          	<type class ="boolean"/>
         </column>
     </stream>

      <stream name="SensorStream" type="pull">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="intColumn">
          	<type class ="integer"/>
         </column>
         <column name="fltColumn">
          	<type class ="float"/>
         </column>
         <column name="strColumn">
          	<type class ="string"/>
         </column>
         <column name="boolColumn">
          	<type class ="boolean"/>
         </column>
     </stream>

      <table name="TestTable">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="integerColumn">
          	<type class ="integer"/>
         </column>
         <column name="floatColumn">
          	<type class ="float"/>
         </column>
         <column name="stringColumn">
          	<type class ="string"/>
         </column>
         <column name="boolColumn">
          	<type class ="boolean"/>
         </column>
     </table>

      <stream name="SimpleStream" type="pull">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="temperature">
          	<type class ="integer"/>
         </column>
         <column name="pressure">
          	<type class ="integer"/>
         </column>
     </stream>

     <table name="Forest" type="push">
     	<!--column name="ts">
     		<type class="timestamp"/>
     	</column-->
         <column name="moisture">
          	<type class ="float"/>
         </column>
         <column name="temperature">
          	<type class ="float"/>
         </column>
     </table>


      <stream name="forestMoisture" type="push">
         <column name="timestamp">
        	<type class ="float"/>
         </column>
         <column name="moisture">
          	<type class ="float"/>
         </column>
     </stream>

	<!-- Testing for the newly created schema, that takes DATs into account. This is a testing
	table for the Linear Regression, so we only have 2 columns. -->
      <table name="forestLRF" isIntensional="true" type="push">
     	<column name="ts">
     		<type class="timestamp"/>
     	</column>
         <column name="temperature">
          	<type class ="float"/>
         </column>
         <column name="moisture">
          	<type class ="float"/>
         </column>
         <datParams type="CLASSIFIER" subtype="LinearRegressionFunction">
			<derivedAttribute name="temperature"/>
			<source>SELECT moisture, temperature FROM Forest[FROM NOW-1 HOUR TO NOW]</source>
         </datParams>
     </table>     


      <stream name="flood" type="pull">
    	<column name="timestamp">
        	<type class ="integer"/>
         </column>
         <column name="temperature">
          	<type class ="integer"/>
         </column>
     </stream>


	<!-- Testing table for D3 algorithm. Example taken from the Design Document (Upd. Grammar) -->
      <table name="d3e" isIntensional="true">
    	<column name="temperature">
        	<type class ="integer"/>
         </column>
         <column name="probability">
          	<type class ="float"/>
         </column>
         <datParams type="OUTLIER_DETECTION" subtype="d3">
			<derivedAttribute name="probability"/>
			<parameters>
				<parameter value="5"/>
			</parameters>
			<source>SELECT s.temperature FROM flood[FROM NOW - 20 MIN TO NOW] s</source>
			<!-- <source>SELECT ts.pressure, ts.temperature FROM TestStream ts</source> -->
         </datParams>
     </table>



</schema>
