=== SNEEManchester/snee/snee/src/main/resources/schema/physical-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--  Copyright (c) The University of Manchester, 2010. -->
<!-- 
  SNEE (Sensor NEtwork Engine)                                              
  http://snee.cs.manchester.ac.uk/                                          
  http://code.google.com/p/snee                                             
                                                                            
  Release 1.x, 2009, under New BSD License.                                 
                                                                            
  Copyright (c) 2009, University of Manchester                              
  All rights reserved.                                                      
                                                                            
  Redistribution and use in source and binary forms, with or without        
  modification, are permitted provided that the following conditions are    
  met: Redistributions of source code must retain the above copyright       
  notice, this list of conditions and the following disclaimer.             
  Redistributions in binary form must reproduce the above copyright notice, 
  this list of conditions and the following disclaimer in the documentation 
  and/or other materials provided with the distribution.                    
  Neither the name of the University of Manchester nor the names of its     
  contributors may be used to endorse or promote products derived from this 
  software without specific prior written permission.                       
                                                                            
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS   
  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR    
  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR          
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,     
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,       
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR        
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              	
 -->

<xs:schema targetNamespace="http://snee.cs.man.ac.uk/namespace/physical-schema" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema">

	<xs:simpleType name="gatewaysType">
		<xs:list itemType="xs:integer"/>
	</xs:simpleType>
	
	<xs:simpleType name="sitesType">
		<xs:list itemType="xs:integer"/>
	</xs:simpleType>

	<xs:complexType name="push_sourceType">
		<xs:sequence>
			<xs:element name="port" type="xs:integer" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="rate" type="xs:double" minOccurs="0"
				maxOccurs="1" default="1.0" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="push_source" type="push_sourceType"/>

	<xs:complexType name="extentType">
		<xs:choice minOccurs="1" maxOccurs="1">
			<xs:element name="sites" type="sitesType" />
			<xs:element ref="push_source"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>
	<xs:element name="extent" type="extentType"/>

	<xs:complexType name="extentsType">
		<xs:sequence>
			<xs:element ref="extent" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="extents" type="extentsType"/>

	<xs:complexType name="sensor_networkType">
		<xs:sequence>
			<xs:element name="topology" type="xs:anyURI" minOccurs="1" maxOccurs="1" />
			<xs:element name="site-resources" type="xs:anyURI" minOccurs="1" maxOccurs="1" />
			<xs:element name="gateways" type="gatewaysType" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="extents" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
	</xs:complexType>
	<xs:element name="sensor_network" type="sensor_networkType"/>

	<xs:complexType name="udp_sourceType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="host" type="xs:anyURI" minOccurs="1"
				maxOccurs="1" />
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="extents" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
	</xs:complexType>
	<xs:element name="udp_source" type="udp_sourceType" />

	<xs:element name="source">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="sensor_network"/>
				<xs:element ref="udp_source"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== SNEEManchester/snee/clients/successorClient/src/main/resources/condorcheck/physicalSchema_query76.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>wsn_query76.xml</topology>
		<site-resources>siteRes76.xml</site-resources>
		<gateways>0</gateways>
		<extents>
			<extent name="A">
				<sites>2,49,11,25,47</sites>
			</extent>
			<extent name="B">
				<sites>47,28,6,46,32</sites>
			</extent>
		</extents> 
	</sensor_network> 
</source>

=== SNEEManchester/snee/clients/successorClient/src/main/resources/testsNatural/physicalSchema_query52.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>testsNatural/wsn_query52.xml</topology>
		<site-resources>testsNatural/siteRes52.xml</site-resources>
		<gateways>0</gateways>
		<extents>
			<extent name="A">
				<sites>36,42,33,17,39,10,19,2,35</sites>
			</extent>
		</extents> 
	</sensor_network> 
</source>

=== SNEEManchester/snee/clients/ecm-client/src/main/resources/RecursiveTest/3main/physical-schema-qep.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>RecursiveTest/3main/wsn1-topology.xml</topology>
		<site-resources>etc/common/tmotesky-site-resources.xml</site-resources>
		<gateways>1</gateways>
		<extents>
			<extent name="Castilla">
				<sites>4,6,8,9,11,12</sites>
			</extent>
		</extents>
	</sensor_network>

</source>

=== SNEEManchester/snee/clients/unreliable-channel-client/src/main/resources/testsSize100/physicalSchema_query82.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>testsSize100/wsn_query82.xml</topology>
		<site-resources>testsSize100/siteRes82.xml</site-resources>
		<gateways>0</gateways>
		<extents>
			<extent name="A">
				<sites>9,21,38</sites>
			</extent>
			<extent name="B">
				<sites>38,16,28</sites>
			</extent>
			<extent name="C">
				<sites>28,5,1</sites>
			</extent>
			<extent name="D">
				<sites>1,29,36</sites>
			</extent>
		</extents> 
	</sensor_network> 
</source>

=== SNEEManchester/snee/clients/failedNodeEvalClientTimeIntergrated/src/main/resources/tests/physicalSchema_query98.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>tests/wsn_query98.xml</topology>
		<site-resources>etc/common/tmotesky-site-resources.xml</site-resources>
		<gateways>0</gateways>
		<extents>
			<extent name="A">
				<sites>14,9</sites>
			</extent>
			<extent name="B">
				<sites>9,6</sites>
			</extent>
			<extent name="C">
				<sites>6,5</sites>
			</extent>
			<extent name="D">
				<sites>5,4</sites>
			</extent>
			<extent name="E">
				<sites>4</sites>
			</extent>
		</extents> 
	</sensor_network> 
</source>

=== SNEEManchester/snee/clients/reliable-channel-client/src/main/resources/condorchecks/physicalSchema_query4.5.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>condorchecks/top4.5.xml</topology>
		<site-resources>condorchecks/siteRes4.5.xml</site-resources>
		<gateways>0</gateways>
		<extents>
			<extent name="A">
				<sites>9,5,7,3,6,0,2,12,10</sites>
			</extent>
		</extents> 
	</sensor_network> 
</source>

=== SNEEManchester/snee/clients/successorClient/src/main/resources/starTopologies/physicalSchema_query1.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns="http://snee.cs.man.ac.uk/namespace/physical-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://snee.cs.man.ac.uk/namespace/physical-schema ../schema/physical-schema.xsd ">

	<sensor_network name="wsn1">
		<topology>starTopologies/wsn_query1.xml</topology>
		<site-resources>starTopologies/siteRes1.xml</site-resources>
		<gateways>0</gateways>
		<extents>
			<extent name="A">
				<sites>1,2</sites>
			</extent>
			<extent name="B">
				<sites>3,4</sites>
			</extent>
		</extents> 
	</sensor_network> 
</source>
